apiVersion: v1
kind: PersistentVolume
metadata:
  name: expense-efs
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: "" # empty as this is static provisioning
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-00cbb3f0e4313c700 # this is joindevops efs volume file system id we have to replace with our's while practicing
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: expense-efs
spec:
  volumeName: expense-efs
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi